# Generated by Django 3.1.4 on 2021-02-18 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20210218_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='creator',
            new_name='user',
        ),
    ]
