# Generated by Django 3.1.4 on 2021-02-19 20:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20210219_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likedbyuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
